# Dockerfile pour compiler piper-phonemize avec Python 3.12
# Basé sur les instructions de https://github.com/rhasspy/piper-phonemize/issues/33

# For Python 3.12
FROM python:3.12.10-bookworm AS build

ARG TARGETARCH
ARG TARGETVARIANT

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        build-essential cmake ca-certificates curl pkg-config git python3 python3-dev python3-pip

WORKDIR /build

COPY ./piper-phonemize/ ./

RUN cmake -Bbuild -DCMAKE_INSTALL_PREFIX=install
RUN cmake --build build --config Release
RUN cmake --install build

# Do a test run
RUN ./build/piper_phonemize --help

# Build .tar.gz to keep symlinks
WORKDIR /dist
RUN mkdir -p piper_phonemize && \
    cp -dR /build/install/* ./piper_phonemize/ && \
    tar -czf "piper-phonemize_${TARGETARCH}${TARGETVARIANT}.tar.gz" piper_phonemize/

# Build Python wheel
ENV CPLUS_INCLUDE_PATH=/build/install/include
ENV LIBRARY_PATH=/build/install/lib

WORKDIR /build

RUN python3 -m pip install --upgrade pip setuptools wheel pybind11 --break-system-packages
RUN python3 setup.py sdist bdist_wheel
RUN cp dist/*.whl /dist/

# -----------------------------------------------------------------------------

FROM scratch

COPY --from=build /dist/piper-phonemize_*.tar.gz ./
COPY --from=build /dist/*.whl ./ 