# config/tts.yaml
# Configuration unifiée du système TTS SuperWhisper V6

# ===================================================================
# SECTION PRINCIPALE
# ===================================================================
# Activation du handler Piper natif (performance optimale <120ms)
# Mettre à `false` pour forcer l'utilisation du fallback Piper CLI.
enable_piper_native: true

# ===================================================================
# CONFIGURATION DES BACKENDS
# ===================================================================
backends:
  # 🚀 PHASE 3: Priorité 1 - Handler natif optimisé (binding Python)
  piper_native_optimized:
    enabled: true
    model_path: "D:/TTS_Voices/piper/fr_FR-siwis-medium.onnx"
    model_config_path: "D:/TTS_Voices/piper/fr_FR-siwis-medium.onnx.json"
    device: "cuda:0"  # RTX 3090 dédiée TTS
    speaker_id: 0
    target_latency_ms: 80  # Objectif optimisé <80ms vs 120ms
    
  # 🚀 PHASE 3: Priorité 1bis - Handler daemon (pipeline asynchrone)
  piper_daemon:
    enabled: false  # Expérimental, activer si binding Python indisponible
    model_path: "D:/TTS_Voices/piper/fr_FR-siwis-medium.onnx"
    executable_path: "piper/piper.exe"
    speaker_id: 0
    target_latency_ms: 50  # Objectif daemon <50ms
    daemon_port: 0         # Port automatique
    daemon_host: "127.0.0.1"
    max_retries: 3
    retry_delay: 1.0

  # Priorité 2: Fallback natif (CLI subprocess)
  piper_native:
    enabled: true
    model_path: "D:/TTS_Voices/piper/fr_FR-siwis-medium.onnx"
    model_config_path: "D:/TTS_Voices/piper/fr_FR-siwis-medium.onnx.json"
    device: "cuda:0"  # Pointera vers RTX 3090 après CUDA_VISIBLE_DEVICES
    speaker_id: 0
    target_latency_ms: 120

  # Priorité 2: Fallback fonctionnel (CPU)
  piper_cli:
    enabled: true
    model_path: "D:/TTS_Voices/piper/fr_FR-siwis-medium.onnx"
    executable_path: "piper/piper.exe" # Chemin vers l'exécutable
    speaker_id: 0
    target_latency_ms: 1000

  # Priorité 3: Fallback Windows natif (CPU)
  sapi_french:
    enabled: true
    voice_name: "Microsoft Hortense Desktop"
    rate: 0      # Vitesse de -10 (lent) à 10 (rapide)
    volume: 100  # Volume de 0 à 100
    target_latency_ms: 2000

  # Priorité 4: Ultime filet de sécurité
  silent_emergency:
    enabled: true
    log_level: "CRITICAL"
    alert_webhook: null # Optionnel: URL d'un webhook pour recevoir les alertes
    target_latency_ms: 5

# ===================================================================
# CONFIGURATION DES COMPOSANTS
# ===================================================================
# 🚀 PHASE 3: Cache LRU optimisé pour textes récurrents
cache:
  enabled: true
  max_size_mb: 200              # Augmenté pour plus de textes
  max_entries: 2000             # Limite nombre d'entrées
  ttl_seconds: 7200             # 2 heures (augmenté)
  eviction_policy: "LRU"        # Least Recently Used
  enable_compression: false     # Compression audio (optionnelle)
  enable_persistence: false     # Persistance sur disque (optionnelle)
  maintenance_interval_seconds: 300  # Maintenance toutes les 5min

# Disjoncteur pour isoler les backends défaillants
circuit_breaker:
  failure_threshold: 3 # Nombre d'échecs avant d'ouvrir le circuit
  reset_timeout_seconds: 30 # Temps avant de retenter un appel

# Monitoring via Prometheus
monitoring:
  prometheus_enabled: true
  prometheus_port: 9090
  log_performance_metrics: true
  alert_on_fallback: true # Log une alerte si un fallback est utilisé

# ===================================================================
# PARAMÈTRES AVANCÉS - PHASE 3 OPTIMISATIONS
# ===================================================================
advanced:
  # Fraction de VRAM allouée au processus TTS sur le GPU.
  # Laisser ~90% pour le LLM.
  gpu_memory_fraction: 0.1
  # Nombre de workers pour traiter les requêtes TTS en parallèle
  async_workers: 2
  # 🚀 PHASE 3: Limite augmentée pour textes longs
  max_text_length: 5000  # Augmenté de 1000 → 5000 chars
  # Nettoyage automatique du texte (caractères non supportés, etc.)
  sanitize_text: true
  # Paramètres audio pour conversion PCM → WAV
  sample_rate: 22050
  channels: 1
  
  # 🚀 PHASE 3: Configuration chunking intelligent
  text_chunking:
    enabled: true
    max_chunk_length: 800          # Sécurité vs limite backend
    min_chunk_length: 50           # Éviter chunks trop courts
    overlap_chars: 20              # Chevauchement pour fluidité
    speech_rate_cps: 15.0          # Vitesse parole (chars/sec)
    inter_chunk_silence_ms: 200    # Pause entre chunks audio
  
  # 🚀 PHASE 3: Configuration GPU optimisée
  gpu_optimization:
    # Réaffectation GPU: STT sur cuda:1, TTS sur cuda:0
    tts_device: "cuda:0"           # RTX 3090 pour TTS
    stt_device: "cuda:1"           # RTX 4060 Ti pour STT
    enable_gpu_streams: true       # Streams dédiés
    memory_pool_size_mb: 512       # Pool mémoire GPU TTS

# ===================================================================
# FEATURE FLAGS (Pour déploiement progressif)
# ===================================================================
feature_flags:
  # Flag principal pour activer le nouveau manager
  use_unified_tts: true
  # Flag pour forcer l'ancien mode (si un handler unique était utilisé)
  enable_legacy_mode: false 